// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw_Tv7A1DUxhg_9n-grPnodEDC7v6vWMc',
    appId: '1:245116794298:android:1d1cc63ad49e6ec3f71983',
    messagingSenderId: '245116794298',
    projectId: 'join-me-mobile',
    storageBucket: 'join-me-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw_Tv7A1DUxhg_9n-grPnodEDC7v6vWMc',
    appId: '1:245116794298:ios:VOTRE_IOS_APP_ID',
    messagingSenderId: '245116794298',
    projectId: 'join-me-mobile',
    iosBundleId: 'com.joinme.mobile',
    storageBucket: 'join-me-mobile.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw_Tv7A1DUxhg_9n-grPnodEDC7v6vWMc',
    appId: '1:245116794298:web:joinme-web-app',
    messagingSenderId: '245116794298',
    projectId: 'join-me-mobile',
    authDomain: 'join-me-mobile.firebaseapp.com',
    storageBucket: 'join-me-mobile.firebasestorage.app',
  );
}
